version: 2

references:
  set-container: &set-container
    docker:
      - image: circleci/node:erbium-buster # node 12 on debian 10
    working_directory: ~/repo

jobs:
  build:
    <<: *set-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run build

  deploy:
    <<: *set-container
    steps:
      - run:
          name: Deploy to ERG server
          command: |
            scp -r ./build/* $SSH_USER@$SSH_HOST:/var/www/html/tots

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
